### ISSUE TITLE
Endpoint port issue?

### ISSUE THREAD

**Issue by burakkaraceylan** [Derek-R-S/Light-Reflective-Mirror#21]
Hello,

On Ubuntu 18.04 when I run sudo dotnet LRM.dll there is an error about an endpoint service.

Starting Endpoint Service... Server: listening port=7777
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.CheckDisposed()
   at System.Net.HttpListener.Stop()
   at Grapevine.RestServer.Start() in C:\Users\scott\source\grapevine\src\Grapevine\RestServer.cs:line 174
   at LightReflectiveMirror.Endpoints.EndpointServer.Start(UInt16 port)
FAILED
Please run as administrator or check if port is in use.

**Comment by burakkaraceylan** [comment]
Geez it was the endpoint port being used by another process. Sorry.
