### ISSUE TITLE
V12 crash on debian

### ISSUE THREAD

**Issue by illiftwhat** [Derek-R-S/Light-Reflective-Mirror#41]
Hello,
I am developing, I have the node server which is launched on debian by "screen -dmSL servrelay dotnet LRM.dll".

And since these last days, the server crashed randomly or so during my test and debug but I did not make any changes in LRM, only listed my game.

I have UseEndpoint, EndpointServerList and EnableNATPunchtroughServer enabled in the config
and i use KcpTransport

this is my log (sorry i have only that):

> Unhandled exception. System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
>    at System.String.Substring(Int32 startIndex, Int32 length)
>    at System.Net.HttpListenerRequestUriBuilder.GetPath(String uriString)
>    at System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath()
>    at System.Net.HttpListenerRequestUriBuilder.Build()
>    at System.Net.HttpListenerRequest.FinishInitialization()
>    at System.Net.HttpConnection.OnReadInternal(IAsyncResult ares)
>    at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Net.ContextAwareResult.Complete(IntPtr userToken)
>    at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()

Thanks for help

**Comment by Oyshoboy** [comment]
Same issue here, looks like this package is not production ready. I recommend you to switch solution.

**Comment by Artars** [comment]
Same, happened recently to me as well. I've been running a LRM node server since December, and this is the first time it happened.

**Comment by illiftwhat** [comment]
> Same, happened recently to me as well. I've been running a LRM node server since December, and this is the first time it happened.

the same thing, the server was running continuously since February and it only happens now, like some kind of bot attack on the server with http requests.

i disabled UseEndpoint and EndpointServerList and the server has not crashed since these changes

**Comment by Oyshoboy** [comment]
I'm using it on Ubuntu btw, and looks like it's comes from this issue: https://github.com/dotnet/runtime/issues/72748, so yeah HTTP endpoints better be avoided for better stability
